import './_vendor';
import vars from './_vars';
import './_functions';
import './components/_modal-window';
import './components/_vacancy-window';
import './components/_repair-window';
import './components/_application-window';
import './components/_simpleBar';
import './components/_productFilters';
import './components/_productSlider';
import './components/_cartLogic';
